<a href="https://colab.research.google.com/github/anoy1729/mlresources/blob/master/Nsl_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import cv2
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [52]:
img = cv2.imread('final.jpg', 1)
print(img)

[[[212 220 237]
  [211 219 236]
  [212 219 238]]

 [[214 222 239]
  [204 212 229]
  [197 204 223]]

 [[189 194 219]
  [168 173 198]
  [147 152 177]]]


In [66]:
r,g,b = cv2.split(img)
print(img)

[[[212 220 237]
  [211 219 236]
  [212 219 238]]

 [[214 222 239]
  [204 212 229]
  [197 204 223]]

 [[189 194 219]
  [168 173 198]
  [147 152 177]]]


In [62]:
numr = np.array(r)
numg = np.array(g)
numb = np.array(b)
print(r)
print(g)
print(b)

[[212 211 212]
 [214 204 197]
 [189 168 147]]
[[220 219 219]
 [222 212 204]
 [194 173 152]]
[[237 236 238]
 [239 229 223]
 [219 198 177]]


In [64]:

rsum = numr.sum(axis=1)
gsum = numr.sum(axis=1)
bsum = numr.sum(axis=1)
print(rsum)
print(gsum)
print(bsum)


[635 615 504]
[635 615 504]
[635 615 504]


In [67]:
rmean = numr.mean(axis=1)
gmean = numr.mean(axis=1)
bmean= numr.mean(axis=1)
print(rmean)
print(gmean)
print(bmean)

[211.66666667 205.         168.        ]
[211.66666667 205.         168.        ]
[211.66666667 205.         168.        ]
